# docker-compose.yml
version: '3.8'

volumes:
  userdb_vol:

networks:
  micro_network:
    name: kong-isky-net
    external: true

services:
  auth-api:
    container_name: cont-audit-mservice
    build:
      context: .
    ports:
    - "5000:5000"
    networks:
      - micro_network
    restart: always
